### ISSUE TITLE
Undefined playerList

### ISSUE THREAD

**Issue by miguelarman** [Pechente/minecraft-telegram-bot#1]
I just cloned this repository to use on my minecraft server. After setting up all of Telegram's end (bot, group, ids, etc), as well as enabling query-mode and opening the port in the firewall, I tried executing the script manually using
`php index.php`

However, it does not work, as the player list is not returned, and is stored as `false`:
```
PHP Notice:  Undefined variable: playerList in /tmp/minecraft-telegram-bot/index.php on line 42
PHP Warning:  sort() expects parameter 1 to be array, bool given in /tmp/minecraft-telegram-bot/index.php on line 43

Execution time: 0.073215007781982
```

I am using minecraft version 1.12.2, I do not know if that may be the problem, because I cannot find much information online about query mode.

Thanks in advance for your help!

**Comment by Coderwelsch** [comment]
hey man, i just forked this repo to fix those issues. I was able to fix the problems you and me encountered and will fix them in my fork.

**Comment by Pechente** [comment]
Nice! @Coderwelsch - if you want to, you can create a pull request. I haven't touched this project in ages but if people are using it, I will maintain it.

**Comment by Coderwelsch** [comment]
Dear @Pechente, thank you for your reply! I thought this repo wasn’t maintained anymore :-P. I’ve also updated the readme a bit to help others setting it up. I’ll create a pr tomorrow or something 😋.

Thank you for your work and see you later 👋

**Comment by Coderwelsch** [comment]
@miguelarman will be fixed when PR was merged into this repo. Please try it again and inform me about further issues … :-)

**Comment by Pechente** [comment]
I merged the PR, thanks a lot @Coderwelsch!
