### ISSUE TITLE
Suspicious link in Readme

### ISSUE THREAD

**Issue by miguelarman** [Pechente/minecraft-telegram-bot#5]
Hello,
In the Readme file, in the Step 5 (Get ID of the (super-)group or channel), the link that is written is ```web.telegram[.com]```. However, the real URL should be ```web.telegram[.org]```. In fact, the ```[.com]``` site seems quite nefarious, giving in fact TLS certificate errors and redirecting to a different site.
This should be a really simple change, so I can create a pull request just for this if you want, but maybe it is easier if you can easily change it directly in the repo.
Thanks!

**Comment by Pechente** [comment]
Thanks for noticing it. It's fixed now.
